### ISSUE TITLE
webpack-glsl-loader

### ISSUE THREAD

**Issue by wolfgangvonludwigsburg** [hendriklammers/rxjs-webgl#1]
webpack.config.js,
change:
`loader  : 'webpack-glsl',`
to:
`loader`  : `'webpack-glsl-loader',`

BTW, very nice!
Thank you!!
PS: I just learn ..., may I ask: do you got more of this cool stuff ?

**Comment by hendriklammers** [comment]
Thanks!
I used the loader from [here](https://github.com/grieve/webpack-glsl-loader) and just used the settings from it's readme, although both seem to work. Have to say I'm not much of a Webpack expert, usually I just copy/paste what I need 😄 

Not sure what you mean by 'cool stuff', but something I recently did for learning more about WebGL shaders was [this](https://github.com/hendriklammers/month-of-shaders). It's completely written in Elm though, but the actually GLSL shaders can be found in the `src/Shader` directory...
